import type { Metadata } from "next";
import "@/app/lib/Sass/Main.scss";
import "./globals.css";
import MainContainer from "@/Containers/Main_Container/MainContainer";
import { Toaster } from "react-hot-toast";
import AuthProvider from "@/Context/AuthContext";

export const metadata: Metadata = {
  title: "Chat-Bot",
  description: "Generated by Sajad Zhianjoo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <AuthProvider>
          <MainContainer theme="light">{children}</MainContainer>

          <Toaster position="top-center" reverseOrder={false} />
        </AuthProvider>
      </body>
    </html>
  );
}
